#!/usr/bin/env bash
set -e

weekdays=("Sun" "Mon" "Tue" "Wed" "Thu" "Fri" "Sat")
months=("Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec")
contributions=($(gh api graphql -f query='{
  viewer {
    contributionsCollection {
      contributionCalendar {
        weeks {
          contributionDays {
            contributionCount
          }
        }
      }
    }
  }
}' --cache 24h --jq '..|.contributionCount?'))

color_number=5
color_first=231
color_decrement=6
color_text=255

tput init

printf "    "
month_current=$(date +%m)
for month in {0..11}; do
    month_this=$(( month+month_current ))
    if (( month_this > 12 )); then
        month_this=$(( month_this-12 ))
    fi
    printf "%s${months[$month_this-1]}      " "$(tput setaf $color_text)"
done
printf "\n"
for day in {0..6}; do
    printf "%s${weekdays[$day]} " "$(tput setaf $color_text)"
    for week in {0..51}; do
        number="contributions[$day+$week*7]"
        if (( number > color_number )); then
            number=$color_number
        fi
        color=$(( color_first - number * color_decrement ))
        printf "%s\U25a2 " "$(tput setaf $color)"
    done
    printf "\n"
done
