#!/usr/bin/env bash

color_text=255
colors=(250 225 224 219 218 213 212 207 206 201 200)
weekdays=("Sun" "Mon" "Tue" "Wed" "Thu" "Fri" "Sat")
months=("Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec")
contributions=($(gh api graphql -f query='{
  viewer {
    contributionsCollection {
      contributionCalendar {
        weeks {
          contributionDays {
            contributionCount
          }
        }
      }
    }
  }
}' --cache 24h --jq '..|.contributionCount?'))

tput init
month_current=$(date +%m)
printf "    "

for month in {0..11}; do
    month_this=$(( month+month_current ))
    if (( month_this > 12 )); then
        month_this=$(( month_this-12 ))
    fi
    printf "%s${months[$month_this-1]}      " "$(tput setaf $color_text)"
done

printf "\n"

for day in {0..6}; do
    printf "%s${weekdays[$day]} " "$(tput setaf $color_text)"
    for week in {0..51}; do
        number="contributions[$day+$week*7]"
        if (( "$number" >= "${#colors[@]}" )); then
            number=${colors[${#colors[@]}]}
        fi
        printf "%s\U25a8 " "$(tput setaf ${colors[number]})"
    done
    printf "\n"
done
